/**
 * Dari Alphabet Data
 * All 32 letters with pronunciation and audio support
 */

export interface DariLetter {
  id: string;
  letter: string;
  name: string;
  sound: string;
  phonetic: string;
  audioUrl?: string;
}

export const dariAlphabet: DariLetter[] = [
  { id: "alef", letter: "ا", name: "Alef", sound: "a", phonetic: "alef" },
  { id: "be", letter: "ب", name: "Be", sound: "b", phonetic: "be" },
  { id: "pe", letter: "پ", name: "Pe", sound: "p", phonetic: "pe" },
  { id: "te", letter: "ت", name: "Te", sound: "t", phonetic: "te" },
  { id: "se", letter: "ث", name: "Se", sound: "s", phonetic: "se" },
  { id: "jeem", letter: "ج", name: "Jeem", sound: "j", phonetic: "jeem" },
  { id: "che", letter: "چ", name: "Che", sound: "ch", phonetic: "che" },
  { id: "he", letter: "ح", name: "He", sound: "h", phonetic: "he" },
  { id: "khe", letter: "خ", name: "Khe", sound: "kh", phonetic: "khe" },
  { id: "dal", letter: "د", name: "Dal", sound: "d", phonetic: "dal" },
  { id: "zal", letter: "ذ", name: "Zal", sound: "z", phonetic: "zal" },
  { id: "re", letter: "ر", name: "Re", sound: "r", phonetic: "re" },
  { id: "ze", letter: "ز", name: "Ze", sound: "z", phonetic: "ze" },
  { id: "zhe", letter: "ژ", name: "Zhe", sound: "zh", phonetic: "zhe" },
  { id: "seen", letter: "س", name: "Seen", sound: "s", phonetic: "seen" },
  { id: "sheen", letter: "ش", name: "Sheen", sound: "sh", phonetic: "sheen" },
  { id: "sad", letter: "ص", name: "Sad", sound: "s", phonetic: "sad" },
  { id: "zad", letter: "ض", name: "Zad", sound: "z", phonetic: "zad" },
  { id: "taa", letter: "ط", name: "Taa", sound: "t", phonetic: "taa" },
  { id: "zaa", letter: "ظ", name: "Zaa", sound: "z", phonetic: "zaa" },
  { id: "ayn", letter: "ع", name: "Ayn", sound: "'", phonetic: "ayn" },
  { id: "ghayn", letter: "غ", name: "Ghayn", sound: "gh", phonetic: "ghayn" },
  { id: "fe", letter: "ف", name: "Fe", sound: "f", phonetic: "fe" },
  { id: "qaf", letter: "ق", name: "Qaf", sound: "q", phonetic: "qaf" },
  { id: "kaf", letter: "ک", name: "Kaf", sound: "k", phonetic: "kaf" },
  { id: "gaf", letter: "گ", name: "Gaf", sound: "g", phonetic: "gaf" },
  { id: "lam", letter: "ل", name: "Lam", sound: "l", phonetic: "lam" },
  { id: "meem", letter: "م", name: "Meem", sound: "m", phonetic: "meem" },
  { id: "noon", letter: "ن", name: "Noon", sound: "n", phonetic: "noon" },
  { id: "waw", letter: "و", name: "Waw", sound: "w/o/u", phonetic: "waw" },
  { id: "he2", letter: "ه", name: "He", sound: "h", phonetic: "he" },
  { id: "ye", letter: "ی", name: "Ye", sound: "y/i", phonetic: "ye" },
];

/**
 * Letter Forms Data
 * Shows how each letter changes in different positions
 */

export interface LetterForms {
  id: string;
  letter: string;
  name: string;
  isolated: string;
  initial: string | null;
  medial: string | null;
  final: string | null;
  connectsBothSides: boolean;
}

export const letterForms: LetterForms[] = [
  {
    id: "alef",
    letter: "ا",
    name: "Alef",
    isolated: "ا",
    initial: null,
    medial: null,
    final: "ـا",
    connectsBothSides: false,
  },
  {
    id: "be",
    letter: "ب",
    name: "Be",
    isolated: "ب",
    initial: "بـ",
    medial: "ـبـ",
    final: "ـب",
    connectsBothSides: true,
  },
  {
    id: "pe",
    letter: "پ",
    name: "Pe",
    isolated: "پ",
    initial: "پـ",
    medial: "ـپـ",
    final: "ـپ",
    connectsBothSides: true,
  },
  {
    id: "te",
    letter: "ت",
    name: "Te",
    isolated: "ت",
    initial: "تـ",
    medial: "ـتـ",
    final: "ـت",
    connectsBothSides: true,
  },
  {
    id: "se",
    letter: "ث",
    name: "Se",
    isolated: "ث",
    initial: "ثـ",
    medial: "ـثـ",
    final: "ـث",
    connectsBothSides: true,
  },
  {
    id: "jeem",
    letter: "ج",
    name: "Jeem",
    isolated: "ج",
    initial: "جـ",
    medial: "ـجـ",
    final: "ـج",
    connectsBothSides: true,
  },
  {
    id: "che",
    letter: "چ",
    name: "Che",
    isolated: "چ",
    initial: "چـ",
    medial: "ـچـ",
    final: "ـچ",
    connectsBothSides: true,
  },
  {
    id: "he",
    letter: "ح",
    name: "He",
    isolated: "ح",
    initial: "حـ",
    medial: "ـحـ",
    final: "ـح",
    connectsBothSides: true,
  },
  {
    id: "khe",
    letter: "خ",
    name: "Khe",
    isolated: "خ",
    initial: "خـ",
    medial: "ـخـ",
    final: "ـخ",
    connectsBothSides: true,
  },
  {
    id: "dal",
    letter: "د",
    name: "Dal",
    isolated: "د",
    initial: null,
    medial: null,
    final: "ـد",
    connectsBothSides: false,
  },
  {
    id: "zal",
    letter: "ذ",
    name: "Zal",
    isolated: "ذ",
    initial: null,
    medial: null,
    final: "ـذ",
    connectsBothSides: false,
  },
  {
    id: "re",
    letter: "ر",
    name: "Re",
    isolated: "ر",
    initial: null,
    medial: null,
    final: "ـر",
    connectsBothSides: false,
  },
  {
    id: "ze",
    letter: "ز",
    name: "Ze",
    isolated: "ز",
    initial: null,
    medial: null,
    final: "ـز",
    connectsBothSides: false,
  },
  {
    id: "zhe",
    letter: "ژ",
    name: "Zhe",
    isolated: "ژ",
    initial: null,
    medial: null,
    final: "ـژ",
    connectsBothSides: false,
  },
  {
    id: "seen",
    letter: "س",
    name: "Seen",
    isolated: "س",
    initial: "سـ",
    medial: "ـسـ",
    final: "ـس",
    connectsBothSides: true,
  },
  {
    id: "sheen",
    letter: "ش",
    name: "Sheen",
    isolated: "ش",
    initial: "شـ",
    medial: "ـشـ",
    final: "ـش",
    connectsBothSides: true,
  },
  {
    id: "sad",
    letter: "ص",
    name: "Sad",
    isolated: "ص",
    initial: "صـ",
    medial: "ـصـ",
    final: "ـص",
    connectsBothSides: true,
  },
  {
    id: "zad",
    letter: "ض",
    name: "Zad",
    isolated: "ض",
    initial: "ضـ",
    medial: "ـضـ",
    final: "ـض",
    connectsBothSides: true,
  },
  {
    id: "taa",
    letter: "ط",
    name: "Taa",
    isolated: "ط",
    initial: "طـ",
    medial: "ـطـ",
    final: "ـط",
    connectsBothSides: true,
  },
  {
    id: "zaa",
    letter: "ظ",
    name: "Zaa",
    isolated: "ظ",
    initial: "ظـ",
    medial: "ـظـ",
    final: "ـظ",
    connectsBothSides: true,
  },
  {
    id: "ayn",
    letter: "ع",
    name: "Ayn",
    isolated: "ع",
    initial: "عـ",
    medial: "ـعـ",
    final: "ـع",
    connectsBothSides: true,
  },
  {
    id: "ghayn",
    letter: "غ",
    name: "Ghayn",
    isolated: "غ",
    initial: "غـ",
    medial: "ـغـ",
    final: "ـغ",
    connectsBothSides: true,
  },
  {
    id: "fe",
    letter: "ف",
    name: "Fe",
    isolated: "ف",
    initial: "فـ",
    medial: "ـفـ",
    final: "ـف",
    connectsBothSides: true,
  },
  {
    id: "qaf",
    letter: "ق",
    name: "Qaf",
    isolated: "ق",
    initial: "قـ",
    medial: "ـقـ",
    final: "ـق",
    connectsBothSides: true,
  },
  {
    id: "kaf",
    letter: "ک",
    name: "Kaf",
    isolated: "ک",
    initial: "کـ",
    medial: "ـکـ",
    final: "ـک",
    connectsBothSides: true,
  },
  {
    id: "gaf",
    letter: "گ",
    name: "Gaf",
    isolated: "گ",
    initial: "گـ",
    medial: "ـگـ",
    final: "ـگ",
    connectsBothSides: true,
  },
  {
    id: "lam",
    letter: "ل",
    name: "Lam",
    isolated: "ل",
    initial: "لـ",
    medial: "ـلـ",
    final: "ـل",
    connectsBothSides: true,
  },
  {
    id: "meem",
    letter: "م",
    name: "Meem",
    isolated: "م",
    initial: "مـ",
    medial: "ـمـ",
    final: "ـم",
    connectsBothSides: true,
  },
  {
    id: "noon",
    letter: "ن",
    name: "Noon",
    isolated: "ن",
    initial: "نـ",
    medial: "ـنـ",
    final: "ـن",
    connectsBothSides: true,
  },
  {
    id: "waw",
    letter: "و",
    name: "Waw",
    isolated: "و",
    initial: null,
    medial: null,
    final: "ـو",
    connectsBothSides: false,
  },
  {
    id: "he2",
    letter: "ه",
    name: "He",
    isolated: "ه",
    initial: "هـ",
    medial: "ـهـ",
    final: "ـه",
    connectsBothSides: true,
  },
  {
    id: "ye",
    letter: "ی",
    name: "Ye",
    isolated: "ی",
    initial: "یـ",
    medial: "ـیـ",
    final: "ـی",
    connectsBothSides: true,
  },
];